language: node_js
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_17d5860a9a31_key -iv $encrypted_17d5860a9a31_iv
  -in ./travis-ci/accounts.enc -out ./travis-ci/accounts.json -d
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: devplat-external-sdk-accounts+npm@squareup.com
  api_key:
    secure: QsAC4FX9z2wiVLZSGnQOGDjES/Bu92TQwt2Kvtuybd+/8/bouwmyCfapI+SUiQO0w8azbw+Uf4Gopjg3XF43gMenfwqQcgFAMAx56in0kGx5PROHgleAcTvo9ncUPB7FeHNG/LZhDDqTjvDtH89dM3yjurtX4VIp5dDYQvvieLPHJELld+F+E26S3uRG4VHlr+o23wm65mJY0l8EPRp5NUcS/yRxw9N21ZfnMJvWgN+6m4ov0/WBwM0Fr7lLqBpvnVCWB0NqszEVEX89lqfl+FKHaaTNMpD0IdAg8sH4Gg8zkmw1+EvgW47dM+ipisZuxyq8CQkH/OiZoMDRnk+aObDmIzT5GV87OOICUCaMUgaa9OGdIfXjs3xiNJ2vEPEEcjqHu7v+DW6gM8wkaWwMr3eRj9wkkipPzhzoEDb/GSDgUxsa/1fwoQ1ovphX+V6EUvkXGAmVP/t3Jp21r+dE2tUE8Q2hqsJV31tmjJ+AXjeiqQuOpwODKWkGf0nr7zS1ddk3pdOS5KNsuBXtLWLXwghZO3p5At1xd9HWZ3xq0KEmBZqCUyXCeGP0/AjXZN4JurGRUosfjAe1XXg8gwEnZ+B1qe+di/sqqCGJCtSIB8jK3eE3Xz8LIH5JMzh9/N8bwnvOxgC0R8ZHGq6SJDcRjK8XmkGJOxR9PbaLiFrAVB8=
  on:
    branch: master
notifications:
  slack:
    secure: CbOyvps2/8XQ5KdKsFzhE/8RTixfS32siYE/KP84ZngspU7HGCQDrt49fWnvrKwtJ2egQecZDSKCP4wVG972oGyUMBfnvxRkZDCK6u81x/u057ZlQe6WlNPbN9ULGjU3QRRhixggEFNDnviv9ukE++pVMMsuhNpFW1Fzr9hPiDBilWQRsStU09bhwwGCkvZWGMEqwk6iIuj4BG2RX3Fr6LGoAjRK6PVGa25PyJCGNORU3zHVU4GTujs54epAWr4jpfKJnfknIk+E7jQ41LHDOBSihrss20yM1oFpcMHTv7oh8Dzm+rFWgvsy6XWI0Q127cGHVjDhDAlzF4k4m3zi5CwsDujrD1aAMNWQD1HiF4OR1WNViQS/E0OOvy0mbyDrhex4x75vBIutShnjmMBSy458o8lkhCs8wmHHXHo76viq9Fqcn8Q0Z8wcBYi496fI39KPajtz//2su02labXCLK4ouNJxB4RQAVJvYwWROvIUtENvM7kdzc7h5kRVHCImfBcWzK9LkiCBFPXi9xJAk4NLFR4aQlNiFHmq3LCu/B/bCgahWDdlLW6MXMLbtJCVpk3t4VpiB/n9UQQJUlGjwYGvXIuuJh8tOY6CDirjsyOcMBP0D/7o9TuV6V97BkETbK/pybe7PuTVCLxI9iz6HfALqqQBFf296XyHNuvDeOg=
    on_success: change
    template:
        - "@oncall"
        - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
  email:
    recipients:
      - devs-apex-alerts+travis@squareup.com
    on_success: change
